### PR TITLE
Replace SpiderMonkey with Duktape

### PR DESCRIPTION
**Pull request by sdrik**
This PR will track my work on the replacement of the SpiderMonkey JS engine by Duktape (see #47).
It is still work in progress and received almost no testing, I only checked that the standard import_script.js works for my audio collection.

### CODE REVIEW

**Comment by v00d00** [comment]
Nice! Thanks for the patch. You will have to give me a couple of days to review this one. Any chance you can give me an overview to help with review?

**Comment by sdrik** [comment]
As said before, this is work in progress, so I'm not sure it should go in yet. There are still areas which need improvement (like locking and destructors).
I kept as much as possible of the existing implementation, so the flow is the same as before: each specialized script is encapsulated in a subclass of the Script base class, with pretty much the same public interface.
There is one shared Duktape heap allocated in the Runtime singleton. Each Script instance get one dedicated Duktape context (basically a stack and a global environment). As heaps are not thread-safe I used mutex-locking for proper isolation.
There are several places where value are not passed between (internal) functions by argument but through the stack. The advantage is that it was easier to follow the existing code that way, the drawback is one need to keep in mind the status of the stack throughout the flow. For example, when a script is compiled in the _load() method it is left on the stack, then _execute() method can pick it up. Another example is the various setProperty/getProperty which act on the object present on the top of the stack instead of receiving a pointer. This will certainly need to be refined at some point.

**Comment by v00d00** [comment]
Hows progress?

**Comment by sdrik** [comment]
It's hopefully in good shape now for a review, but probably not bug free...

**Comment by v00d00** [comment]
Hi, sorry about introducing the conflicts by removing the DVD stuff.

Can you rebase please? Thanks!

**Comment by sdrik** [comment]
No problem at all.
PR rebased.

**Comment by v00d00** [comment]
So this is really great, thanks! I've had look now and I like it so far. I will finish up on Monday most likely but 👍!

**Pull request merged**
